asp.net.Students/Areas/Student/Controllers/ResultController.cs
using asp.net.Students.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace asp.net.Students.Areas.Student.Controllers;
[Area("Student")]
[Authorize(Roles = "Student, Admin")] 

public class ResultController : Controller
{
    private readonly SiteContext _context;
    private readonly UserManager<User> _userManager;

    public ResultController(SiteContext context, UserManager<User> userManager)
    {
        _context = context;
        _userManager = userManager;
    }
    public async Task<IActionResult> Index()
    {
        var user = await _userManager.GetUserAsync(User);

        if (await _userManager.IsInRoleAsync(user, "Teacher") || await _userManager.IsInRoleAsync(user, "Admin"))
        {
            var results = await _context.QuizStudentResults
                .Include(a => a.Quiz)
                .ThenInclude(q => q.Questions)
                .ThenInclude(x => x.Options)
                .ToListAsync();

            return View(results);
        }
        else
        {
            var userResults = await _context.QuizStudentResults
                .Include(a => a.Quiz)
                .ThenInclude(q => q.Questions)
                .ThenInclude(x => x.Options)
                .Where(a => a.Student.Id == user.Id)
                .ToListAsync();

            return View(userResults);
        }
    }

    public async Task<IActionResult> Show(int id)
    {
        QuizStudentResult result = (await _context.QuizStudentResults
            .Include(r => r.StudentAnswers)
            .Include(r => r.Quiz)
            .ThenInclude(q => q.Questions)
            .ThenInclude(x => x.Options)
            .FirstOrDefaultAsync(r => r.Id == id))!;
        return View(result);
    }
    
}

asp.net.Students/Areas/Student/Views/Result/Index.cshtml
@model List<QuizStudentResult>

<table class="table table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Title of test</th>
        <th>Score</th>
        <th>Pass date</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @if (Model != null)
    {
        foreach (var result in Model)
        {
            <tr>
                @{
                    var maxScore = result.Quiz.Questions.Sum(x => x.Options.Sum(o => o.Value));
                }
                <td>@result.Id</td>
                <td>@result.Quiz.Title</td>
                <td>@Math.Round(result.Score,2) / @maxScore</td>
                <td>@result.CreatedAt</td>
                <td>
                    <a class="btn btn-primary"
                       asp-area="Student"
                       asp-controller="Result"
                       asp-action="Show"
                       asp-route-id="@result.Id">Show</a>
                </td>
            </tr>
        }
    }
    </tbody>
</table>

asp.net.Students/Areas/Student/Views/Result/Show.cshtml
@model QuizStudentResult

<div class="d-flex flex-column align-items-center">
    <div class="d-flex justify-content-between w-75">
        @{
            var maxScore = Model.Quiz.Questions.Sum(x => x.Options.Sum(o => o.Value));
        }
        <h2>@Model.Quiz.Title</h2>
        <h4>@Math.Round(Model.Score, 2) / @maxScore</h4>
    </div>
    <div class="w-100">
        @foreach (var question in @Model.Quiz.Questions)
        {
            float scoreByQuestion = 0;
            <div class="p-3 m-3 border border-dark rounded-3 d-flex flex-column-reverse">
                <div>
                    @foreach (var option in @question.Options)
                    {
                        var isCorrect = option.Value > 0;
                        var isUserSelected = Model.StudentAnswers.Any(answer => answer.Option.Id == option.Id);
                        var textColor = isCorrect ? "green" : "red";
                        var bgColor = isCorrect && isUserSelected ? "rgba(0, 128, 0, 0.3)" : (!isCorrect && isUserSelected ? "rgba(255, 0, 0, 0.3)" : "white");
                        scoreByQuestion += isCorrect && isUserSelected ? option.Value : 0;
                        <p class="m-0" style="color: @textColor; background-color: @bgColor; padding: 5px;">@option.Text</p>
                    }
                </div>
                <h4>
                    @question.Text 
                    <span class="badge bg-primary">@Math.Round(scoreByQuestion, 2)</span>
                </h4>
            </div>
        }
    </div>
</div>